### ISSUE TITLE
多值查询如何传递参数？

### ISSUE THREAD

**Issue by fengmk2** [aleafs/itier-client#5]
如 WHERE id in (123,456)，如何变换成 WHERE id in (:r1, :r2), {r1: 123, r2: 456} ，还是说要调用者自己处理呢？

**Comment by aleafs** [comment]
WHERE id IN (:id), {'id' : [123, 456]}
这是我要的效果，如果不是，那就是bug

**Comment by fengmk2** [comment]
已经实现了？

Sent from my iPhone

On 2012-4-10, at 7:39, aleafs
reply@reply.github.com
wrote:

**Comment by fengmk2** [comment]
no need to fixed.
